version: '3.1'
services:
  joomla:
    build: .
    restart: always
    links:
      - joomladb:bitnami/mariadb
    ports:
      - 8080:80
    volumes:
      - "./volumes/site:/var/www/html"
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: pass
  joomladb:
    image: bitnami/mariadb:latest
    ports:
      - 3306:3306
    restart: always
    volumes:
      - "./volumes/data:/bitnami/mariadb/data"
    environment:
      MARIADB_DATABASE: ead
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: pass