version: '3.1'
services:
  joomla:
    build: .
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    volumes:
      - "./volumes/site:/var/www/html"
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: aVerySecurePasswordTh4atIs_Complex
  joomladb:
    image: mysql:5.6
    ports:
      - 3306
    restart: always
    volumes:
      - "./volumes/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: aVerySecurePasswordTh4atIs_Complex